=== Carlos-Gamarra554/Visual-Studio/XML/ProyectoIntermodular/LIBR_FISICO/LIBR_FISICO.dtd
<!DOCTYPE libr_fisico [
<!ELEMENT libr_fisico (libro*)>
<!ELEMENT libro (cod_libro, ISBN, num_paginas)>
<!ELEMENT cod_libro (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT num_paginas (#PCDATA)>
]>

=== Carlos-Gamarra554/Visual-Studio/XML/ProyectoIntermodular/LIBR_FISICO/LIBR_FISICO.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libr_fisico SYSTEM "LIBR_FISICO.dtd">
<libr_fisico>
    <libro>
        <cod_libro>1</cod_libro>
        <ISBN>9783161484100</ISBN>
        <num_paginas>600</num_paginas>
    </libro>
    <libro>
        <cod_libro>2</cod_libro>
        <ISBN>9783161484117</ISBN>
        <num_paginas>417</num_paginas>
    </libro>
    <libro>
        <cod_libro>3</cod_libro>
        <ISBN>9783161484124</ISBN>
        <num_paginas>554</num_paginas>
    </libro>
    <libro>
        <cod_libro>5</cod_libro>
        <ISBN>9783161484131</ISBN>
        <num_paginas>132</num_paginas>
    </libro>
    <libro>
        <cod_libro>4</cod_libro>
        <ISBN>9783161484148</ISBN>
        <num_paginas>223</num_paginas>
    </libro>
</libr_fisico>
